import type { Metadata } from "next";
import { Montserrat, Sansita } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/widgets/navbar";
import Footer from "@/components/widgets/footer";
import { createClient } from "@/lib/supabase/server";

const montserrat = Montserrat({subsets: ["latin"]})
const sansita = Sansita({subsets: ["latin"], variable: "--font-sansita", weight: ["400", "700", "800", "900"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const supabase = createClient()
  const {data: {user}} = await supabase.auth.getUser()

  return (
    <html lang="en" className={`${sansita.variable}`}>
      <body
        className={`${montserrat.className} antialiased`}
      >
        <NavBar user={user}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
